---
# Ansible playbook to install OS packages required by Vim plugins

- name: Install required DEB packages for default Vundle plugins
  apt: name={{ item }}
  with_items: "{{ vimansible_default_plugins|default([])|selectattr('required_debs', 'defined')|map(attribute='required_debs')|list }}"
  when: ansible_os_family == 'Debian'
        and vimansible_default_plugins is defined
        and vimansible_install_packages_for_plugins == True

- name: Install required DEB packages for more Vundle plugins
  apt: name={{ item }}
  with_items: "{{ vimansible_more_plugins|default([])|selectattr('required_debs', 'defined')|map(attribute='required_debs')|list }}"
  when: ansible_os_family == 'Debian'
        and vimansible_more_plugins is defined
        and vimansible_install_packages_for_plugins == True
